### ISSUE TITLE
Do better property checking

### ISSUE THREAD

**Issue by fidian** [fidian/PrettyCSS#16]
It doesn't make sense to have this:

``` css
div {
    background-color: green;
    background: url('/images/bg.jpg');
}
```

In the above example, `background` wipes out `background-color`.  This program should issue a warning that the property will overwrite another.
