### ISSUE TITLE
Star hack and underscore hack for property names

### ISSUE THREAD

**Issue by fidian** [fidian/PrettyCSS#3]
IE doesn't mind having stars or underscores before property names, like this:

``` css
p.boxy {
    width: 10px;
    _width: 11px;  /* IE6 */
    *width: 12px; /* IE7 and below */
}
```

Would it be possible to add support for these hacks?

http://stackoverflow.com/questions/7484653/star-hack-not-working-in-ie6-and-8
http://en.wikipedia.org/wiki/CSS_filter
