### ISSUE TITLE
Tokenizer hangs on regexp match with long URL

### ISSUE THREAD

**Issue by outoftime** [fidian/PrettyCSS#47]
The following CSS causes the PrettyCSS parser to hang indefinitely:

```css
h1{color: purple;}
p{color: blue;} 
body{font-family: Arial;
font-size: 14px;
background-color: pink;} 
body{background-image: url("data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMVFRUXFxcXFxcVFxUVFRcXFRUWGBUXFRcYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLysBCgoKDg0OGhAQGi0fICUtLS0tLS0tLS0tLS0tLS0tLS8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0rLS0tK//AABEIAQcAvwMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAEAQIDBQYABwj/xAA/EAABAwIEAwUGBAQEBwEAAAABAAIRAyEEBRIxQVFhBiJxgZEHEzKhsfBCcsHRFCNS4WJzgvEVM2OSk8LSU//EABkBAAMBAQEAAAAAAAAAAAAAAAABAgMEBf/EACgRAAICAgEDBAEFAQAAAAAAAAABAhEDITESQVEEEzLw0SJxgZHBI//aAAwDAQACEQMRAD8A27WqVrVzWqRrV0EHNantalaFIGoAQNTw1KAngJAIGqRrVzQsD7QfaKzBzQw+mpiPxTdtMEbujd23d9eCG6A2Gc53hsIzXiKzKQ4aj3nRwa0XcfALw72idr6WNrtdQa/QwFoc8BurqGgkgeMHoFkcxx9SvUNWs9z3ncuMnwHIdAhPJZuVlUEuxTk33x5lQhyUlSMma880RTxJ8UCHLg5AFoKw5ehTw4bAjw4qtbXKf7ziE7FRb1sK5rWuOx5IrFP10WO4tMFBZfmzNJp1QdJ2MSAeaJaHBpb+BxsTx6hZtu99jtiopPp4a2vD/A/MCSymSOClc7ThwP6ipXZPUIA1AgbBR53bQwcApTTqKOicJwU8slWkiqSpVy6DyRq5OSQgD6MaFIAkATwFYhQE8BIE4IAcAnAJAq/tHnDMJhqld+zG2Gxc7ZrR1JgeaAMx7Tu2n8FSFKiQcRUFrSKbeLyOfIc78F4HUqEkucS5xJJJMkkmSSTuSeKKzjMqmIrPrVTL3mTxgcGjoBYIGJWTdlpHak4NSsYrnLMsLiPopboai2VtPCE8N1OzLX8t1usuyZjR3gCeCOOBBuAB4fsuZ+pVnVH0ra2ebHLnjgmVMIQCV6RXy2ZsJPECUFislB4EnxsmvUIT9Mzzw0yFy1ePyOOBtwAhZ/EYYtMEH9VtGalwYSg48gvmrDBZgdHunGQDLenMeCAdThN+qurFGTjwbPKs1NmOE8AUzPMK41AQPispuzbabmB4HeiD0I3hGZ3XDWCD3psuXqrJ+lHue25ek/6ytc/wA18vpU6cu+KPmqRSVKpcZcSUwLqhFpbdnj+oywyNdEelL7s5InQuVnOfRwTwmhOCsBwTwmhPagBwXiPtl7Qe9xAwzT3KN3AGxqEcfAfUr1jtXnIwmFqVjEgQ0Hi82aPX5L5oxtQuJc4kucS5xO5JMyT6qZMaAybqalTkqJqssvp3krJspBeBwHH/AH6LW5ZhdA6/dkJluHPxG33uVd4amuLNkvR34MVbZNSYiW01JQooylhyuajsQGGqN7FanCqCrhiOCVAVNYTuFnc2wA4Cx+S1tegqvFUpBBWuObizHLjUkedY3D6T0Qi0mZ4U3B4ceYWeqMgr0Iys8yUaZNgMe+kYabK6o4SvXIIa508eCzg3W2wfaiqykxtNo2vZWkrsHOTj0t68FNjcI6k8seIIUIRGOxbqry95uVArMjkiVcgD6PCcEgCcFYDgnhNC6o8NaSdgCfRAHlHtmzbU+lhWmzf5j+U7MB+ZXlmL49IC0HabMPf4qrUOxcQPAWH7+az1e/hcrJspA1NaXKMOLWWboi612SN7qxyuom2FXIvsO1WmEag8HTVthqa89npxLLB0gVd4bDNhVmBar2hGlVFCmxpwohAYiiFbONrnwQWIZP31TkiYsz+LYqXFM3WgxjVU4tgG5CyNnwZ7G0QQsZmtHS5b7EtWQzunddmB9jg9RHuUPFXeT5yaDo0tdIi6pWfEFJiGRB6rrRxlo90knmZSKOi6QFIrIOXLl0oA+kAnhMCdKsB4Kz/bvM/cYR5BhzhpHSeKvgvL/a5mYJbSB+HfxIFvnM+KTegR5k7Y+BQ9Yd3yU1O4I6foomt1QOZA/RZFgmH3C2eBaGtCoMwwAY4FkxFwdwVoaAlgI5Bc+V2kdGKLTZc4LLXVBL6mgcGt/U80U/KHsuytI5SWn5WKzbs8LBvsYM2S0+1DJvrcI3YALzedXT5rFRn2R0uWJcs1GHxtemeLh5H6LQZbmhd8QgrF5dm9Oq8tp6+Jh4h0CL2sRc7clpKRLYlRJNco0j0vh2aV1eyps0zZ7bMBJ8EWf+Xq5Kme4vJjgpsqiuq1cRU+JxaPEN+idSySmRL6hJ6fuUHnGKNGJDnEiQG3IE7v5A3jnflegxWevMlrHhtzYlwaOEmI5eq2UZta0YynjTp2zQYzLG0703n8pgg+HIrL54209U+jnbn2J/tt8lJ2jb/KB6rSCa+RjlcX8eDKj4kTiGjSbclHTw/wk8Zt4Ix9KWho4hdCORjsurs0QWmeacrbsj2Mr4pxaxzRHNap3slxvB1M+ZWhDPP1y3bvZTjv+mfMqJ3suzD+lh/1f2QB62Eqio1JAI4ifVSKgErVNLSV4P29xuut6ne8G4keZPmF6/2szFtGg5zyQD3RG8utPkJXg/aLFtqVnvb8JPdn+kWaPIW8lMmOIBQepMIYe08nD5GUPRN1IFmyzV59RBJIHH5CyJy+nMBOxOJaaRZpJeQDIvAgaifmkwBgwd1yP4nbH5EWb9nw7vsEniJ3RQpvqU6dMUQw05gtJaCDEiI3+EzK0OAaCrahg28lMcrSouWCL2ZfLsvcG+7DGmXBweWu1tjYhwdY3dPOeK0mMGmmxpgvG5AgH9lZMohoJVBmNe9+amc2y8eNRLBteKJbxQOVvJa9rYDnDdwkC4O3Hw4pDW7uyEy/Ed+FCZo0SYjDPbTfQcKZDyHGoWO1lzRZxdrvyvwKoGUKtEOLGAl4IkySA497jckgXK9EZTDm3Q1bAt5LX3Wc/sqzzzBdnGx7yo2HXsLD0CTOKUhg6x6rXZiAAsvj6kOaRu06v+3n0unCbk9iyY1FaKvtDSaGYfSNJ0vDxx1NLLnxF/NVtMfD97FXna7E0qvu30rC4LZnSbb9Y+ioaX4fErqx/E48vyPSvZPXjERzC9qC8A9ndfTi2dbL35hstnwYsVKuCVSBkMH8Dfyj6IgFD4Ud1vgPoiAtAMN7Wnxh2Dm/6Af/AF8l4xiSvX/bA/8AkUv8z/1K8dqrOXJceBKW6e07JtILnmFIzWZW/wB4Wk7ENad76YnbmifhqEddzx6oTszmNAUX0qzg2H+9aS4sPwQWh0xPdFtMmd7QSauMpVHh1JwcA1oMcCufIqZ04pGiy2tcLU4N0rFZc9arLq2y5Hyehyi3qQGknYAn5LIlgcdb3CSdp+QWmx9cRA2P0VF/CNgtLWvB/qANvFNkIsKRo+5MgyNuqz5psLu64BwuBIn0Vucvb8LXFrOLQNvyngoWYRrNTKbWtbMyGief6oGaDLXa6TXjlcciLO+ajxdQBMyWoKY0cOvM7/VDZq+5Qwit7KLNMRuqnLaAq1XB3whl7czt8gpcyqXUeVYqhoLXVmMeXO1TUZTOlrAYl5A4bSJWmNNrRlmkk9mczakQYHwBzoJ4SbN6GIPkgqZP1PzVvnuYYctLaFQVNb2OcDTd3AymxoLajiBJcKhMN2IgxM04Nh5/VdsVSPOk7Z2BzurRrB9MiQbSFvKPtUx4A/5R/wBJ/deYVPjVvT2VpkG+HtZxv9NL0P7qVvtcxnGnSPqvPVyBUfQmH2HgPop5UNDYeAT6roaVoI819sVXuUm8dRPyI+q8mcV6N7Xa81GDiBHgDcesH0Xm5KylyWuCaiLpKu08fsfolw5uF1Ru6QzqbrK27Mm5HOD6Kl2CsMqr6HNPkfMpSVxaKg6kmbvBNgq7oVIVJg3ghW+DeCbrzWtnqReg6tiQBc8FWPzUOMNIjmm5tlweZBPrbwhVdHDaTDm+cSFcUikXH/EY/FP09Zt8/JRDNNLr3Cg/gGfFqEeJiw5cFXYtgJho8wFo4oDXYXEBwkFD4qvuEF2fwoYHF7jfYTb0S4yoJKxaFZUY925WHpVZL327znHymB8lo+0+N0U3Xue6PP7lZBjoELswRpWef6iVyJy+XffRGUz9+MqtYbo5rr+f7LYwBKourOibBVtY95WGHNk0Jkq5cuTEfQtHZR42ppaZ9OJPAJWFZ/tPmgpUnPm8d3a7iIb5b+U8loSeV+0LG+8xBGqYPe/NAEDoNh5rKFFY+uX1HOJ57oaFkzRDqG48URWFyoKG4RFXf0+gSAjDP5c8f7JoNktV0CPvZRSmhGzyrElobOxAhaPDVQdlmsvp6qbfAIrD13UzfbmuCatnpQdJGtp3RVPANdvHmqnB4kEC6vMBVE3usjYhfkLOnkShquXhmy09Z9OLLP5hVEmCmxLZXOMKqzDFBsknZPzPMGsBJKzdfVV7z7M3Def5unRVCPdkTl2Rn85xpq1P8Ldv3QgCWu+XOP8AiP1suaV3pUqPNbt2Opm8osPv6oT91IDxTELXv98UdhTYIB5keaNwjpCaEwldKQFLCYj3fG4kNYfuT92XknbjOS90auYaOA5u/QeBWu7WZw1jCQeBawXvaHu+cenNeTYysXuLuJ+Xh0TkwigYBOLLJNSc6pZQUOoMuPVPr81B71MqPJG6AG1XSlcmC6Iw9EueAPHyRdIKNlk4hgHQK4OFDhCqcu4LSYNtl50+T1Ma0VAwb2HuHyO3keCKoZjWZvScfyw4fv8AJW9TD8V1Kip6i+nwVtTtGf8A8qv/AI3/ALKsxea1n/DRcOryGj03Woq0fD5ICthwna8CcX5M5Qy0udrqu1O4f0t8B+qbmztLT4FaF9KAstnsw6/A/RXD9Utmc10x0YsFSU1CCngrvPOJCbp7jYKHUnApASjZF4JyBa778kXgimhMOBSyoy5I5yokKz7NDUeb2Fhy8lQ1anJJXqqDUpLJNSTUmSiaODqO2afOyTY0rIZTS6bBXWF7PudBcfL+60GX5Oxgs0T97lZyyxRpHDJlP2cyE1G1HvEaQAGkwTrkTpF7WM7SIvIBuMXlfuajmaA0shsQAYAkF3Ekg7m+0rRZMzSSwfjGmBTFRxMy0NG4kjcIbO6H4rTcESS7uwNdSdi4kiOAaPPN5HKJccajIr8uatJg2qky+lsrzCrmlydkOCwaLJwYlphENpqTSwOqxCuajq7OqEcgAHHGyymatkFaTHPlUWOZYq4aZlk2jz9wgkckoK0GdZEG0W4imTsXVQ5zbS8Mb7sC++uQeABWdC9A8wfKUFMJTmlAEoRGHKElT4dyaEw4uSi6UhOYFRI5uRt4knzUrMpYPwg+N1fe4SDDrheVs9H2YrsVVPDNb+EI3D1WbEBG0aM2Rf8AwQOGylystQrgjoFh5IppHBV9XJXtu0kKIOqs3bPgpK2i8wlYte1zSWkHcbibSPKVYYmiH6i/3ml51RUOl7wNTg6Y0m5bxnvLMDMwNwQfRaJuMNRjQ3W576YBOltRrQR/LZTIOlj2gg3IgCI71tcSfBz5mlsDZhjTJY6NTTBggieO3LbyVhQaomvLzpj3jw150tc0tYRpBqVKmzhfYb92brqlXRMd5oIbrAOkktDok8Y4dCs8kK2a4sienyW2GCLIVPg8xCsRjAVmbiVigMVYI2rVCq8yrhICtqhBYmjIKKqYsRCnwY1CQJAnwLmwdEwYnmrim3ozySSVsSjhw2iG6jqawgsa5pkudq0kR/LcLSTMixjjjc57Nhr3hrXUyCe6+JA4B0QJiLgDwXpAoEa9TSQabtRa01HkNu33oMFgHd74H4xuLGhxFBo/DpBAc0FwcdJHduLG3QbbDZdU24rRx44qTpnmWIwb2fE0+O4UAK9CrUmlVWJyWk7bunonHLfIpYWuDKBS0jdWlbs+8HuODh1sUFUwNVh7zHDrEj1C1TTMnFoLY5ShQsNlIFZmbt9EAphoI2phXW7wIkcL2hMrmJlpgcuXgvNaPWvyQtpI7BVYQn8Q0g6SJ5HnwT8NXDtt4B9QD+qWx2i8LmkXQ78KxyFNTquFZFjIcTlo5JgwoDdJDzAOgNiNRm7pMAC/AkzCMFeVPTdsYB6EwDYxMcJgx0Ti6ZM1aAP4cAkAAAsb3Gt0h2kwJDIAvJLje3HgfSa0hzqhpwxzS2lDgHz3YAadw0GXc4mZU2DoNEAkNmdTosBdzrDYb9FG6mS0OtqLWizQLgQwWHeNwJ3K06u5j0Lj6gH+FI0iCHOPKGkOjQQTzn5HzkLCJF7cRcf7IoDS9xDAQ1xEO7zR+CXzM9/YeEREhHsGlrS0wJuHaQ4MEBsDiCT073pMooqM5ffvgD1nmp6WELyBuXGBNgTyBNkW4RUefeWFMt1EAt0im06GiDJ3bMEmOZTWCGMmdILmAHU4Na5oc4zsCTqnvaja0CUvbS5H7ra0Vgy9kguGpsu1AAgwDpbDgIu428E84dzID9A0aBsHapYBaACHQ7d3PjCtdDodTGkGp7t0AnQ1uoPbHKLifFROjSWOeSwuLrXAMRIEXaYFupWsWo6MpJy3yB4U06b4LXyKZBfAL6cxqg6TYEiHG946IDPIqOb/ADKj4Ed4AAbWDgZd5jebndWLmOhzXNe46muu5o1Nm7Wk3mDvsR1iax7Ru2YkxqjVHCYtMckpt0PFGLkB/wAEEZh8raeCiEo/B1YWFs6kkDvwAHBKMGCrsUQ4KI4UhFsfTEocRk1M7safkfUKnxXZ9v4HFvQ3H7rbnDoPEYXorjmnHuZzwQl2JSVHUbIITnKMuUNjSI/diLwTb5KEUGggi0cttovzU7yoXotjpEVYOII1AgjiL/L7so3veANuF+O6lK7SixdJIwm9vC+/ToisNXcIBYfUWF0OwImmYRY6JsBVcQQ6b+7cJFwWTPCxJI4iyOdUHEkdW/ECbNI8HFvgg2PU7ONyJEGOIkGCeUjbir6raszcKTruLALgCBIEzM7k6ieJdMX6nmom09XMjTp/1Pc4v0/4btud4J2IUrnnTFjBqEjSJHwgaiLkESR4HkExroDvx3I/zNIgxEwCAdpsq7f1+SLt/tf4HvrOfre4hziC5xN2gNAaXC99IADfLfi/USANQDGkPLSbl8aGlg490unyKFeYbv8AE1zRH9RiJuO7AdMyOkwQ4VbRpmIvJhknlx1RF/6Um/8ARpVr9iaodL7D8x4EuJMT+WLcJThTduG90Q2RtMT3jzM/RR1yNIJJ1TAb+EtIcXO/NIA9Fx0lhm2lr3NAEk1NOlkngOaHt7fKBaWlwxlTT+IkR8LmjvNtAiI6X3VcWW/frujJUNQKHJtUaqCTtAT2rmWKlco3JDLbAVdldUqQcsrh6sK9y/E9UhhxwqGxGElXWGeHJa9McFVCsw5UL3QoGYlD1q2t8DYbpBdBm6UU1LQp2RTKKKCwH3KcKaPNIKJ1JFBZCGJzE/SkaeiQx7ERTKgYFO0IAJ3+UgzBAN2njBFvNQVqZa0HiJghoMO0kAaTaLxBBGw4yJqSmaVUZNESgpJgfuCG2BaGBofewa7utAncl0X5crJuIoWIk7sIbAIdEnVMS0t6G8gXm1m6iHc7xI4HSSWz4ElMqUk+quCei3vyAOZbrcXExPEcj99EhYp3thC1HKLNEqG1FASkqOKgc9AxzwoHFI6oo3PTFY9rkdha8KsBStrQkNGvwOMR/wDESOqyGGxquKOLlKx0YP35gAbn7lWODpaQFWYBsXO5V7hqSt+DOPkKoIoOQzVM0IQ2Shy6ErEQ2nPgmLgELE3Si3MULmJNFJjAYUjXKOEoUlEnvIRFF6D1KajUSAtaKfVATcO6BJQWLxM2CokZiHKvqAojTJUjaSQwAUymOoqz9ymuooGU9SihqlNXb6KHfQRYqKV0hNKscRh1W1acKkS9Dg8hG4bGQq4OTmi6XSCkQZPSnvHyV6zZcuTfJMeCVpU1MLlyYydl0WwrlyYhwZKifRXLkMaIalNQuC5cs2aIZCfRmQALcf08Vy5IZb1nwxVoErlyZIQ2kp6dJcuTQEgpJr6S5cgVg9WmoDSSrkigXE0lV4mkkXJolle4QUrasLly0Ri2f//Z
```

I have tracked the issue down to the [regexp match in the tokenizer](https://github.com/fidian/PrettyCSS/blob/master/lib/tokenizer.js#L348), specifically against the [`URL` pattern](https://github.com/fidian/PrettyCSS/blob/master/lib/tokenizer.js#L158). Presumably given the behavior, this is something along the lines of [catastrophic backtracking](http://www.regular-expressions.info/catastrophic.html), although a visual inspection of the expression does not yield any obvious suspects.

It appears that the behavior obtains for pretty much any valid long data URI inside an incomplete `url()` property.

I poked through the tokenizer’s system for building up the token expressions a bit, but got lost in the indirection—was hoping maybe you had an idea of how this might be fixed @fidian?

Much appreciated!
